/** lab11-2functs.c
* ===========================================================
* Name: David Petzold
* Section: T6/7
* Project: Lab 11-2
* Purpose: Implementation file for lab11-2.h
* ===========================================================
*/

#include "lab11-2functs.h"
#include <ctype.h>

//All function definitions suggested/generated by GitHub Copilot

bool isFirstHalfAlpha(char theChar) {
    return (theChar >= 'a' && theChar <= 'm') || (theChar >= 'A' && theChar <= 'M');
}

int typeOfChar(char theChar) {
    if (theChar == 'a' || theChar == 'e' || theChar == 'i' || theChar == 'o' || theChar == 'u' ||
        theChar == 'A' || theChar == 'E' || theChar == 'I' || theChar == 'O' || theChar == 'U' ||
        tolower(theChar) == 'y') {
        return CHAR_IS_VOWEL;
    } else if ((theChar >= 'a' && theChar <= 'z') || (theChar >= 'A' && theChar <= 'Z')) {
        return CHAR_IS_CONSONANT;
    } else {
        return CHAR_IS_OTHER;
    }
}

bool isMagicChar(char theChar) {
    return theChar == MAGIC_CHAR;
}